[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "msp430-quickstart"
version = "0.1.0"

[dependencies]
#panic-halt = "0.2.0"

[dependencies.msp430]
version = "0.1.0"

#[dependencies.msp430-rt]
#features = ["abort-on-panic"]
#version = "0.1.0"

[dependencies.msp430-rtfm]
git = "https://github.com/japaric/msp430-rtfm"

[dependencies.msp430g2553]
features = ["rt"]
version = "0.1.0"

[profile.release]
lto = true
